name: Release Packages

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-graal:
    name: Artifact for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.2.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: Build Native Image
        run: native-image --no-fallback -cp dragapult.app.MainKt -jar dragapult-app/build/libs/dragapult-app.jar dragapult
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: dragapult-${{ matrix.os }}
          path: dragapult*
          retention-days: 1

  release:
    needs: build-graal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dragapult-macos-latest
          path: macos
      - uses: actions/download-artifact@v3
        with:
          name: dragapult-ubuntu-latest
          path: ubuntu
      - uses: actions/download-artifact@v3
        with:
          name: dragapult-windows-latest
          path: windows
      - name: Rename Files
        run: |
          mv macos/dragapult macos/dragapult-mac
          mv ubuntu/dragapult ubuntu/dragapult-linux
          mv windows/dragapult.exe windows/dragapult-windows.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            macos/dragapult-mac
            ubuntu/dragapult-linux
            windows/dragapult-windows.exe
